name: tinify-copy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check last changed files
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
      - uses: namoscato/action-tinify@v1
        with:
          api_key: ${{ secrets.TINIFY_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}      
      - name: repo-sync
        uses: andstor/copycat-action@v3
        with:
          username: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: beep..reCHaRgeD
          clean: true
          personal_token: ${{ secrets.DST_REPO_TOKEN }}
          exclude: .github/*
          src_path: ./
          src_branch: main
          dst_path: /
          dst_branch: main
          dst_owner: robust-wq
          dst_repo_name: cdn
